#!/bin/bash
# Builds/reinstalls "Crypto DCA Tracker.app" into /Applications.
#
# macOS silently refuses to launch app bundles located inside ~/Documents
# (or Desktop/Downloads) via Finder/Dock/Launchpad - a built-in anti-malware
# restriction - so the launchable app must live in /Applications like any
# other Mac app. This script rebuilds it there. The project folder itself
# (app.py, server.py, .venv, backups/, store.json) stays exactly where it is;
# only the tiny launcher bundle moves.
#
# Run this again if: the app doesn't launch, the icon needs updating, or
# Python gets reinstalled/upgraded via Homebrew (the bundle embeds a copy of
# a small binary from the current Python framework install).
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_NAME="Crypto DCA Tracker"
DEST="/Applications/$APP_NAME.app"
ICON_SVG="$PROJECT_DIR/icon.svg"
VENV_PYVENV_CFG="$PROJECT_DIR/.venv/pyvenv.cfg"

if [ ! -f "$VENV_PYVENV_CFG" ]; then
  echo "error: $PROJECT_DIR/.venv not found. Create it first:" >&2
  echo "  python3 -m venv .venv && ./.venv/bin/pip install -r requirements.txt" >&2
  exit 1
fi

# Derive the Python framework's own GUI launcher stub from the venv's base
# interpreter, e.g. .../Versions/3.14/bin/python3.14 -> .../Versions/3.14/Resources/Python.app/Contents/MacOS/Python
BASE_EXE="$(awk -F' = ' '/^executable/{print $2}' "$VENV_PYVENV_CFG")"
FRAMEWORK_VERSION_DIR="$(cd "$(dirname "$BASE_EXE")/.." && pwd)"
PY_STUB="$FRAMEWORK_VERSION_DIR/Resources/Python.app/Contents/MacOS/Python"
PY_VERSION_DIR_NAME="$(basename "$FRAMEWORK_VERSION_DIR")"
VENV_SITE="$PROJECT_DIR/.venv/lib/python$PY_VERSION_DIR_NAME/site-packages"

if [ ! -f "$PY_STUB" ]; then
  echo "error: expected Python GUI stub at $PY_STUB but it's missing." >&2
  echo "Python may have been reinstalled differently - update this script's assumptions." >&2
  exit 1
fi
if [ ! -d "$VENV_SITE" ]; then
  echo "error: expected venv site-packages at $VENV_SITE but it's missing." >&2
  exit 1
fi

echo "Building icon..."
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT
qlmanage -t -s 1024 -o "$WORKDIR" "$ICON_SVG" >/dev/null
mkdir "$WORKDIR/icon.iconset"
sips -z 16 16     "$WORKDIR/icon.svg.png" --out "$WORKDIR/icon.iconset/icon_16x16.png" >/dev/null
sips -z 32 32     "$WORKDIR/icon.svg.png" --out "$WORKDIR/icon.iconset/icon_16x16@2x.png" >/dev/null
sips -z 32 32     "$WORKDIR/icon.svg.png" --out "$WORKDIR/icon.iconset/icon_32x32.png" >/dev/null
sips -z 64 64     "$WORKDIR/icon.svg.png" --out "$WORKDIR/icon.iconset/icon_32x32@2x.png" >/dev/null
sips -z 128 128   "$WORKDIR/icon.svg.png" --out "$WORKDIR/icon.iconset/icon_128x128.png" >/dev/null
sips -z 256 256   "$WORKDIR/icon.svg.png" --out "$WORKDIR/icon.iconset/icon_128x128@2x.png" >/dev/null
sips -z 256 256   "$WORKDIR/icon.svg.png" --out "$WORKDIR/icon.iconset/icon_256x256.png" >/dev/null
sips -z 512 512   "$WORKDIR/icon.svg.png" --out "$WORKDIR/icon.iconset/icon_256x256@2x.png" >/dev/null
sips -z 512 512   "$WORKDIR/icon.svg.png" --out "$WORKDIR/icon.iconset/icon_512x512.png" >/dev/null
cp "$WORKDIR/icon.svg.png" "$WORKDIR/icon.iconset/icon_512x512@2x.png"
iconutil -c icns "$WORKDIR/icon.iconset" -o "$WORKDIR/applet.icns"

echo "Assembling $DEST..."
rm -rf "$DEST"
mkdir -p "$DEST/Contents/MacOS" "$DEST/Contents/Resources"
cp "$PY_STUB" "$DEST/Contents/MacOS/Python"
cp "$WORKDIR/applet.icns" "$DEST/Contents/Resources/applet.icns"

cat > "$DEST/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleName</key>
	<string>$APP_NAME</string>
	<key>CFBundleDisplayName</key>
	<string>$APP_NAME</string>
	<key>CFBundleIdentifier</key>
	<string>com.caseyselph.dca-tracker</string>
	<key>CFBundleVersion</key>
	<string>1.0</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleExecutable</key>
	<string>launcher</string>
	<key>CFBundleIconFile</key>
	<string>applet</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>NSHighResolutionCapable</key>
	<true/>
	<key>LSMinimumSystemVersion</key>
	<string>10.13</string>
</dict>
</plist>
PLIST

cat > "$DEST/Contents/MacOS/launcher" <<LAUNCHER
#!/bin/bash
# Generated by build_app.sh - do not edit directly, edit that instead.
PROJECT_DIR="$PROJECT_DIR"
APP_SCRIPT="\$PROJECT_DIR/app.py"
VENV_SITE="$VENV_SITE"
RUNTIME_PYTHON="\$(dirname "\$0")/Python"

if [ ! -f "\$RUNTIME_PYTHON" ] || [ ! -f "\$APP_SCRIPT" ]; then
  osascript -e 'display dialog "Missing app.py or the bundled Python runtime." buttons {"OK"} default button "OK" with icon stop' >/dev/null 2>&1
  exit 1
fi

cd "\$PROJECT_DIR" || exit 1
export PYTHONPATH="\$VENV_SITE"
exec "\$RUNTIME_PYTHON" "\$APP_SCRIPT"
LAUNCHER
chmod +x "$DEST/Contents/MacOS/launcher"

echo "Signing..."
codesign --force --deep -s - "$DEST"

echo "Registering with Launch Services..."
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$DEST"

echo "Done: $DEST"
echo "(First launch may prompt for Documents-folder access once - that's normal, click Allow.)"
